// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jO8IgSmdNk57zzpRVS5jQEpFDL12l0Q', 
    appId: '1:694797354889:web:7aa5404c528b6d36934358',
    messagingSenderId: '694797354889',
    projectId: 'eventplanner-b1d88',
    authDomain: 'eventplanner-b1d88.firebaseapp.com',
    storageBucket: 'eventplanner-b1d88.appspot.com', 
    measurementId: 'G-04PGLYD9NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7jO8IgSmdNk57zzpRVS5jQEpFDL12l0Q',
    appId: '1:694797354889:android:72e9294a9fafd5c5934358',
    messagingSenderId: '694797354889',
    projectId: 'eventplanner-b1d88',
    storageBucket: 'eventplanner-b1d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0XLjHhwI_DBwblkSC9eEHr8xvCC6mpg',
    appId: '1:694797354889:ios:3b6170d218662306934358',
    messagingSenderId: '694797354889',
    projectId: 'eventplanner-b1d88',
    storageBucket: 'eventplanner-b1d88.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi0XLjHhwI_DBwblkSC9eEHr8xvCC6mpg',
    appId: '1:694797354889:ios:3b6170d218662306934358',
    messagingSenderId: '694797354889',
    projectId: 'eventplanner-b1d88',
    storageBucket: 'eventplanner-b1d88.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMFWhvQZ96Pv2Amio4_IOFwVIspFItEM',
    appId: '1:694797354889:web:d2dd7e26809249c7934358',
    messagingSenderId: '694797354889',
    projectId: 'eventplanner-b1d88',
    authDomain: 'eventplanner-b1d88.firebaseapp.com',
    storageBucket: 'eventplanner-b1d88.appspot.com',
    measurementId: 'G-84VFE4R13R',
  );
}
